gravity_x: 0
gravity_y: -10
FPS:  30
velocity_iterations: 8
position_iterations: 3
move_force: 1500
jump_force: 1600

half_block_len: &len  2

chell_half_width: 1.5
chell_half_height: 1.5
chell_density:  10
chell_gravity_scale:  2

rock_half_len: 1
rock_density: 100 #1000000

acid_half_height: 0.25

button_half_width:  *len
button_half_height: 0.25

gate_half_width: *len
gate_half_height: 4 # 2 * width

enrg_block_half_len:  *len  # Ancho y alto por ser cuerpo cuadrado
time_to_release:  10  # Tiempo que demora en liberar bola de energia

enrg_ball_radius: *len
enrg_ball_density:  1
enrg_ball_force:  100
enrg_ball_lifetime: 5

barrier_half_len: 4 # 2 * len
barrier_half_width: 1

cake_half_len:  *len  #cuerpo cuadrado

portal_half_width: 0.25
portal_half_height: 1.98  # Algo mas chico que el largo del bloque

pintool_half_width: 1
pintool_half_height: 1
pintool_lifetime: 20