world:  # Centrado en x=0, y=width/2
  width: &width  1000
  height: &height 60
box_side_length: &length 4 # Alto/Ancho box en Box2D (metros)
# x, y: posicion central (excepto diagonal)
cake:
  x: 64
  y: 2
chell:
  - id: 0
    x: -20
    y: 2
  - id: 1
    x: -24
    y: 2
  - id: 2
    x: -16
    y: 2
  - id: 3
    x: -14
    y: 2
block_rock:
  - width: *width  # floor
    height: *length
    x: 0
    y: -2
  - width: 20
    height: *height
    x: -40
    y: 30
  - width: 20
    height: *length
    x: 0
    y: 2
  - width: 20
    height: *length
    x: 30
    y: 2
acid:
  - x: 14
    y: 0.25
    width: 4
block_metal:
  - width: 32
    height: *length
    x: 24
    y: 18
  - width: 8
    height: *length
    x: 0
    y: 18
block_metal_diagonal: # posicion de punta inferior izquierda (viendolo como cuadrado)
  - width: *length
    height: *length
    x: 2
    y: 4
    orientation: NE
rock:
  - x: 25
    y: 5
button:
  - id: 0
    x: 50
    y: 0.5
gate:
  - id: 0
    x: 58
    y: 4
    buttons_needed:
      - id: 0
    energy_receiver_needed:
      - id: 0
energy_transmitter:
  - x: 22
    y: 6
    direction: O
energy_receiver:
  - id: 0
    x: 6
    y: 18