world:  # Centrado en x=0, y=width/2
  width: &width  1000
  height: &height 60
box_side_length: &length 4 # Alto/Ancho box en Box2D (metros)
# x, y: posicion central (excepto diagonal)
cake:
  x: 64
  y: 2
chell:
  - id: 0
    x: -20
    y: 2
  - id: 1
    x: -24
    y: 2
  - id: 2
    x: -16
    y: 2
  - id: 3
    x: -26
    y: 2
block_rock:
  - width: *width  # floor
    height: *length
    x: 0
    y: -2
  - width: *length
    height: *height
    x: 72
    y: 30
  - width: 8
    height: *length
    x: 24
    y: 2
  - width: 8
    height: *length
    x: -46
    y: 10
acid:
  - x: -45
    y: 0.25
    width: 8
block_metal:
  - width: 20
    height: *height
    x: -70
    y: 30
  - width: *length
    height: *length
    x: -40
    y: 2
  - width: 12
    height: *length
    x: 5
    y: 18
  - width: 12
    height: *length
    x: 10
    y: 12
  - width: *length
    height: *length
    x: 18
    y: 2
rock:
  - x: 0
    y: 2
  - x: 44
    y: 2
button:
  - id: 0
    x: -46
    y: 12.5
  - id: 0
    x: -46
    y: 12.5
gate:
  - id: 0
    x: 58
    y: 4
    buttons_needed:
      - id: 0
    energy_receiver_needed:
      - id: 0
energy_transmitter:
  - x: 22
    y: 6
    direction: O
energy_receiver:
  - id: 0
    x: 6
    y: 18