# NO ES UN ARCHIVO DE REFERENCIA, SOLO PARA PROBAR VALORES
world:  # Centrado en x=0, y=width/2
  width: &width  1000
  height: &height 60
box_side_length: &length 4 # Alto/Ancho box en Box2D (metros)
# x, y: posicion central (excepto diagonal)
cake:
  x: 150
  y: 2
chell:
  - id: 0
    x: 0
    y: 2
  - id: 1
    x: -5
    y: 2
  - id: 2
    x: -10
    y: 2
  - id: 3
    x: 2
    y: 2
block_rock:
  - width: *width  # floor
    height: 4
    x: 0
    y: -2
  - width: *length
    height: *length
    x: 14
    y: 2
  - width: *length # right_wall
    height: *height
    x: 200   # *width + *length
    y: 16
  - width: 10
    height: *length
    x: -102
    y: 16
block_metal:
  - width: 40
    height: *length
    x: -90
    y: 2
  - width: *length
    height: *length
    x: -96
    y: 6
block_metal_diagonal: # posicion de punta inferior izquierda (viendolo como cuadrado)
  - width: *length
    height: *length
    x: -92
    y: 4
    orientation: NE
#  - width: *length
#    height: *length
#    x: -10
#    y: 1
#    orientation: NO
#  - width: *length
#    height: *length
#    x: 20
#    y: 1
#    orientation: SE
#  - width: *length
#    height: *length
#    x: -20
#    y: 1
#    orientation: SO
rock:
  - x: -120
    y: 4
#  - x: 25
#    y: 50
#  - x: -120
#    y: 30
#  - x: -10
#    y: 2
#acid:
#  - x: -50
#    y: 1
#  - x: -40
#    y: 1
button:
  - id: 0
    x: -120
    y: 1
  - id: 1
    x: 25
    y: 1
gate:
  - id: 0
    x: 60
    y: 4
    buttons_needed:
      - id: 0
      - id: 1
#    energy_receiver_needed:
#      - id: 0
#  - id: 1
#    x: -60
#    y: 1
#    buttons_needed:
#      - id: 1
#    energy_receiver_needed:
#      - id: 0
#      - id: 1
#energy_transmitter:
##  - x: 90
##    y: 2
##    direction: N
##  - x: -114
##    y: 16
##    direction: S
#  - x: -105
#    y: 6
#    direction: E
#  - x: -75
#    y: 6
#    direction: O
energy_receiver:
  - id: 0
    x: -90
    y: 16
  - id: 1
    x: -150
    y: 2
  - id: 2
    x: 10
    y: 2
energy_barrier:
  - x: 80
    y: 4
    orientation: V
  - x: -118
    y: 16
    orientation: H
acid:
  - x: 35
    y: 1

