world:  # Supone centro pantalla en x = 0, y = height/2
  width: &width  100
  height: &height 60
box_side_length: &length 4 # Alto/Ancho box en Box2D (metros)
# x, y: posicion central
block_rock: # Superficies con bloque roca,
  - width: *width  # floor
    height: *length
    x: 0
    y: -2
  - width: *width # roof
    height: *length
    x: 0
    y: 62 # *height + *length/2
  - width: *length # right_wall
    height: *height
    x: 52   # *width/2 + *length/2
    y: 0
  - width: *length # left_wall
    height: *height
    x: -52  # -*width/2 - *length/2
    y: 0
#block_metal
#block_metal_diagonal
  #acid
  #button
  #rock
  #energy_transmitter
  #energy_receiver
  #gate
  #energy_bareer
chell:
  - id: 0
    x: 0
    y: 1

#chell
