#ifndef PORTAL_PROTOCOL_MACROS_H
#define PORTAL_PROTOCOL_MACROS_H

/* Protocolo */
#define BLUE_PORTAL (int16_t) 0
#define ORANGE_PORTAL  (int16_t) 1

#define DONT_DELETE (int16_t) 0
#define DELETE  (int16_t) 1

#define JUMPING   (int16_t) 0
#define NOT_JUMPING   (int16_t) 1

#define PROTOCOL_MOVE_LEFT   (int16_t) 0
#define PROTOCOL_MOVE_RIGHT   (int16_t) 1
#define PROTOCOL_JUMP   (int16_t) 2
#define PROTOCOL_STOP   (int16_t) 3
#define PROTOCOL_SHOOT_PORTAL (int16_t) 4
#define PROTOCOL_SHOOT_PIN_TOOL   (int16_t) 5
#define PROTOCOL_LIFT_ROCK  (int16_t) 6
#define PROTOCOL_DROP_ROCK  (int16_t) 7
#define PROTOCOL_ROCK_BLOCK_DATA (int16_t) 8
#define PROTOCOL_METAL_BLOCK_DATA    (int16_t) 9
#define PROTOCOL_METAL_DIAGONAL_BLOCK_DATA   (int16_t) 10
#define PROTOCOL_ENERGY_TRANSMITTER_DATA (int16_t) 11
#define PROTOCOL_ENERGY_RECEIVER_DATA    (int16_t) 12
#define PROTOCOL_ACID_DATA   (int16_t) 13
#define PROTOCOL_BUTTON_DATA (int16_t) 14
#define PROTOCOL_GATE_DATA   (int16_t) 15
#define PROTOCOL_ENERGY_BARRIER_DATA (int16_t) 16
#define PROTOCOL_ROCK_DATA   (int16_t) 17
#define PROTOCOL_ENERGY_BALL_DATA    (int16_t) 18
#define PROTOCOL_PORTAL_DATA (int16_t) 19
#define PROTOCOL_PIN_TOOL_DATA   (int16_t) 20
#define PROTOCOL_CHELL_DATA  (int16_t) 21
#define PROTOCOL_BUTTON_CHANGE_STATE   (int16_t) 22
#define PROTOCOL_ENERGY_TRANSMITTER_ACTIVATE    (int16_t) 23
#define PROTOCOL_ENERGY_RECEIVER_ACTIVATE    (int16_t) 24
#define PROTOCOL_GATE_CHANGE_STATE  (int16_t) 25

#endif //PORTAL_PROTOCOL_MACROS_H
