#ifndef PORTAL_PROTOCOL_MACROS_H
#define PORTAL_PROTOCOL_MACROS_H

/* Protocolo */
#define BLUE_PORTAL    0
#define ORANGE_PORTAL  1

#define DONT_DELETE 0
#define DELETE  1

#define JUMPING   0
#define NOT_JUMPING   1

#define PROTOCOL_MOVE_LEFT   0
#define PROTOCOL_MOVE_RIGHT   1
#define PROTOCOL_JUMP   2
#define PROTOCOL_STOP   3
#define PROTOCOL_SHOOT_PORTAL 4
#define PROTOCOL_SHOOT_PIN_TOOL   5
#define PROTOCOL_LIFT_ROCK  6
#define PROTOCOL_DROP_ROCK  7
#define PROTOCOL_ROCK_BLOCK_DATA 8
#define PROTOCOL_METAL_BLOCK_DATA    9
#define PROTOCOL_METAL_DIAGONAL_BLOCK_DATA   10
#define PROTOCOL_ENERGY_TRANSMITTER_DATA 11
#define PROTOCOL_ENERGY_RECEIVER_DATA    12
#define PROTOCOL_ACID_DATA   13
#define PROTOCOL_BUTTON_DATA 14
#define PROTOCOL_GATE_DATA   15
#define PROTOCOL_ENERGY_BARRIER_DATA 16
#define PROTOCOL_ROCK_DATA   17
#define PROTOCOL_ENERGY_BALL_DATA    18
#define PROTOCOL_PORTAL_DATA 19
#define PROTOCOL_PIN_TOOL_DATA   20
#define PROTOCOL_CHELL_DATA  21
#define PROTOCOL_BUTTON_CHANGE_STATE   22
#define PROTOCOL_ENERGY_TRANSMITTER_ACTIVATE    23
#define PROTOCOL_ENERGY_RECEIVER_ACTIVATE    24
#define PROTOCOL_GATE_CHANGE_STATE  25

#endif //PORTAL_PROTOCOL_MACROS_H
